-- tests/run_all.lua
require("tests/test_character")
require("tests/test_attack_system")
require("tests/test_controller")
require("tests/test_npc_spawner")
require("tests/test_fight_manager")
require("tests/test_fps_camera")
require("tests/test_fps_map")
require("tests/test_fps_player")
require("tests/test_fps_combat")
require("tests/test_touch_controls")
require("tests/runner").summary()
