-- src/scenes/city_assault.lua
-- Side-scrolling kaiju rampage through a city.
-- Player scrolls left/right through a wide level, finds items, fights to the boss.

local SM      = require("src/scene_manager")
local Ctrl    = require("src/controller")
local Input   = require("src/input")
local AS      = require("src/attack_system")
local AM      = require("src/audio_manager")
local Pool    = require("src/blood_pool")
local NPC     = require("src/npc")
local CPU     = require("src/cpu_controller")
local FR      = require("src/food_renderer")
local SL      = require("src/story_lore")
local LM      = require("src/landmark_defs")
local CR      = require("src/city_renderer")
local KS      = require("src/kaiju_sprites")
local RD      = require("src/restaurant_defs")

local CA = {}
CA.__index = CA

local SCREEN_W  = 480
local SCREEN_H  = 270
local GROUND_Y  = 220
local LEVEL_W   = 4800    -- wide scrolling level
local CAM_LERP  = 5.0

-- Item types scattered through the level
local POWER_NAMES = { "GROUND SLAM", "DASH STRIKE", "SHIELD BURST", "RAGE MODE" }

-- Fart types: cycled on each F press
local FART_TYPES = {
  { name="SILENT BUT DEADLY",   color={0.35,0.75,0.25}, damage=8,  radius=50,  duration=2.0, count=6  },
  { name="FIRE IN THE HOLE!!",  color={1.00,0.38,0.05}, damage=22, radius=38,  duration=1.0, count=4  },
  { name="ARCTIC BLAST",        color={0.30,0.65,1.00}, damage=3,  radius=65,  duration=3.0, count=9,  slow=true },
  { name="MEGA FART — RUN!!",   color={0.88,0.22,0.95}, damage=30, radius=180, duration=1.8, count=14 },
}

local GREGG_BLAME = {
  "IT WAS %s!!",
  "NOT ME — %s DID IT!",
  "%s CROPDUSTED US ALL!",
  "DEFINITELY %s. I SAW IT.",
  "I SWEAR IT WASN'T ME, IT WAS %s!",
}

local GREGG_W, GREGG_H   = 22, 30
local GREGG_SPEED        = 55
local GREGG_FOOD_TRIGGER = 2   -- spawn after this many food items collected

local FOOD_POWERUP = {
  -- Speed surge (10 sec, 2x speed)
  energydrink="SPEED SURGE", coffee="SPEED SURGE", soda="SPEED SURGE",
  juice="SPEED SURGE", boba="SPEED SURGE",
  -- Damage boost (15 sec, 1.6x damage)
  steak="DAMAGE BOOST", lobster="DAMAGE BOOST", turkey="DAMAGE BOOST",
  wings="DAMAGE BOOST", corndog="DAMAGE BOOST", kebab="DAMAGE BOOST",
  -- Rage (fill power meter instantly)
  birthdaycake="RAGE MODE", ramen="RAGE MODE", curry="RAGE MODE",
  noodles="RAGE MODE", friedrice="RAGE MODE",
  -- Everything else defaults to HEAL (+30 HP)
}

-- Buildings and furniture are generated by CR (city_renderer)

local function genEnemies(rng)
  local enemies = {}
  -- Civilians visible immediately
  for i = 1, 8 do
    table.insert(enemies, { x = rng(100, 450), type="civilian", spawned=false })
  end
  -- Police near start (challenge from go)
  for i = 1, 5 do
    table.insert(enemies, { x = rng(220, 600), type="police", spawned=false })
  end
  -- Small monsters throughout (appear early and often)
  for i = 1, 16 do
    table.insert(enemies, { x = rng(250, LEVEL_W-300), type="monster", spawned=false })
  end
  -- Police: scattered mid-level
  for i = 1, 14 do
    table.insert(enemies, { x = rng(600, LEVEL_W-400), type="police", spawned=false })
  end
  -- More civilians fleeing mid-level
  for i = 1, 10 do
    table.insert(enemies, { x = rng(500, LEVEL_W-500), type="civilian", spawned=false })
  end
  -- Tanks: from mid-level
  for i = 1, 7 do
    table.insert(enemies, { x = rng(math.floor(LEVEL_W/2), LEVEL_W-600), type="tank", spawned=false })
  end
  table.sort(enemies, function(a,b) return a.x < b.x end)
  return enemies
end

local function genItems(rng, foodPool)
  local pool = foodPool or FR.TYPES
  local items = {}
  -- Food items (city-themed): scattered ? boxes
  for i = 1, 14 do
    local fx = rng(300, LEVEL_W - 300)
    local fy = GROUND_Y - 16 - rng(0,1)*rng(30,80)
    table.insert(items, {
      x=fx, y=fy, w=16, h=16,
      kind="food", type=pool[rng(1, #pool)],
      collected=false, pulse=rng(0,100)*0.01,
    })
  end
  -- Power unlocks
  for i = 1, 4 do
    local px = rng(600, LEVEL_W - 600)
    table.insert(items, {
      x=px, y=GROUND_Y - 90 - rng(0,60), w=18, h=18,
      kind="power", slot=i, name=POWER_NAMES[i],
      collected=false, pulse=rng(0,100)*0.01,
    })
  end
  -- Speed boost
  for i = 1, 3 do
    table.insert(items, {
      x=rng(400, LEVEL_W-400), y=GROUND_Y-16, w=14, h=14,
      kind="speed", collected=false, pulse=rng(0,100)*0.01,
    })
  end
  return items
end

-- ── Constructor ───────────────────────────────────────────────────────────────

function CA.new(playerCharInfo, bossCharInfo, citiesData, storyCityKey)
  local self = setmetatable({}, CA)

  self._storyCityKey = storyCityKey
  self._audio        = AM.getInstance()
  self._audio:playMusic()

  -- Seeded-ish RNG via closure
  local function rng(a, b) return math.random(a, b) end

  -- Player
  local PMod   = require(playerCharInfo.module)
  self._p1     = PMod.new()
  self._ctrl1  = Ctrl.new(self._p1.character, 80, GROUND_Y)
  self._ctrl1.character = self._p1.character
  self._ctrl1._levelW   = LEVEL_W
  self._maxHP  = self._p1.character.stats.maxHealth

  -- Camera
  self._camX      = 0
  self._levelW    = LEVEL_W

  -- Restaurant (one per city, special cinema power-up)
  self._restDef  = RD.get(storyCityKey)
  self._restX    = math.floor(LEVEL_W * 0.35)  -- at 35% through the level
  self._restUsed = false

  -- World objects (food items use city-specific pool)
  self._buildings = CR.generateBuildings(LEVEL_W, GROUND_Y)
  self._furniture = CR.generateFurniture(LEVEL_W, GROUND_Y)
  self._enemyDefs = genEnemies(rng)
  self._items     = genItems(rng, self._restDef.foods)
  self._npcs      = {}
  self._projectiles = {}

  -- Boss
  self._bossInfo  = bossCharInfo
  self._bossChar  = nil
  self._bossCtrl  = nil
  self._bossCPU   = nil
  self._bossSpawned = false

  -- Blood pool
  self._pool = Pool.new()

  -- City visuals (sky/ground colors from a random city def)
  local cd = citiesData[rng(1, #citiesData)]
  self._skyC  = cd.skyC  or {0.10, 0.14, 0.28}
  self._gndC  = cd.gndC  or {0.22, 0.20, 0.18}
  self._landmark = LM.get(storyCityKey)

  -- Player powers (ASDF)
  self._powers = { false, false, false, false }  -- unlocked by items
  self._powerTimers = { 0, 0, 0, 0 }

  -- Speed buff
  self._speedMult    = 1.0
  self._speedTimer   = 0

  self._damageMult  = 1.0
  self._damageTimer = 0

  -- Dollars / kills
  self._dollars   = 0
  self._killCount = 0

  -- State machine
  self._state     = "FIGHTING"  -- FIGHTING | BOSS | CHOICE | CINEMA | VICTORY | DEFEAT
  self._fadeAlpha = 1.0
  self._fadingIn  = true

  -- Choice
  self._choiceSel   = 1
  self._choiceMade  = false
  self._choicePulse = 0
  self._spared      = false

  -- Cinema scene
  self._cinema      = nil

  -- Announce banner
  self._announce     = nil
  self._announceTimer = 0

  -- Fart state
  self._fartTimer   = 0
  self._fartClouds  = {}
  self._fartTypeIdx = 0   -- cycles through FART_TYPES

  -- Gregg
  self._gregg         = nil
  self._foodCollected = 0

  -- Splat streak
  self._timeAccum  = 0
  self._killTimes  = {}

  -- Screen flash (unleash)
  self._screenFlash = 0

  return self
end

-- ── Camera ────────────────────────────────────────────────────────────────────

function CA:_updateCamera(dt)
  local target = self._ctrl1.x - SCREEN_W / 2
  target = math.max(0, math.min(LEVEL_W - SCREEN_W, target))
  self._camX = self._camX + (target - self._camX) * math.min(1, CAM_LERP * dt)
end

-- ── Enemy spawning (activate when camera reveals them) ────────────────────────

function CA:_activateEnemies()
  local visR = self._camX + SCREEN_W + 120  -- slightly ahead of visible
  for _, def in ipairs(self._enemyDefs) do
    if not def.spawned and def.x < visR then
      def.spawned = true
      local npc = NPC.new(def.x, GROUND_Y, def.type,
        def.type == "tank" and 15000 or 2000)
      table.insert(self._npcs, npc)
    end
  end
end

-- Boss spawns when player reaches 85% through the level
function CA:_checkBossSpawn()
  if not self._bossSpawned and self._ctrl1.x > LEVEL_W * 0.85 then
    self._bossSpawned = true
    local BMod      = require(self._bossInfo.module)
    self._bossChar  = BMod.new()
    self._bossCtrl  = Ctrl.new(self._bossChar.character, LEVEL_W - 160, GROUND_Y)
    self._bossCtrl.facingRight  = false
    self._bossCtrl.character    = self._bossChar.character
    self._bossCtrl._levelW      = LEVEL_W
    self._bossCPU   = CPU.new()
    self._state     = "BOSS"
    self._announce     = "⚠  " .. self._bossInfo.name .. "  APPEARS!"
    self._announceTimer = 2.8
  end
end

-- ── Update ────────────────────────────────────────────────────────────────────

function CA:update(dt)
  -- Fade in
  if self._fadingIn then
    self._fadeAlpha = math.max(0, self._fadeAlpha - dt * 2.5)
    if self._fadeAlpha <= 0 then self._fadingIn = false end
  end

  if self._announceTimer > 0 then self._announceTimer = self._announceTimer - dt end

  if self._state == "VICTORY" or self._state == "DEFEAT" then
    self._fadeAlpha = math.min(1, self._fadeAlpha + dt * 1.5)
    if self._fadeAlpha >= 1 then
      local SS = require("src/story_state")
      local WM = require("src/scenes/world_map")
      if self._state == "VICTORY" and self._storyCityKey then
        SS.conquer(self._storyCityKey)
      end
      SM.replace(WM.new({ won=(self._state=="VICTORY"), cityKey=self._storyCityKey }))
    end
    return
  end

  if self._state == "CINEMA" then
    self:_updateCinema(dt)
    return
  end

  -- Player move
  local moveX = (self._p1.character.isDefeated) and 0 or Input.getMoveX(1)
  local spd   = self._speedMult
  if self._speedTimer > 0 then
    self._speedTimer = self._speedTimer - dt
    if self._speedTimer <= 0 then self._speedMult = 1.0 end
  end
  if self._damageTimer > 0 then
    self._damageTimer = self._damageTimer - dt
    if self._damageTimer <= 0 then self._damageMult = 1.0 end
  end
  -- Temporarily patch moveSpeed for speed buff
  local baseSpd = self._p1.character.stats.moveSpeed
  if spd ~= 1.0 then self._p1.character.stats.moveSpeed = baseSpd * spd end

  self._ctrl1:update(dt, moveX, self._buildings)
  self._p1:update(dt)
  self._p1.attacks:update(dt, self._ctrl1.x, self._ctrl1.facingRight)

  if spd ~= 1.0 then self._p1.character.stats.moveSpeed = baseSpd end

  -- Player death
  if self._p1.character.isDefeated then
    self._state     = "DEFEAT"
    self._fadeAlpha = 0
    return
  end

  self:_updateCamera(dt)
  self:_activateEnemies()
  self._pool:update(dt)

  -- Fart clouds
  self._fartTimer = math.max(0, self._fartTimer - dt)
  for i = #self._fartClouds, 1, -1 do
    local fc = self._fartClouds[i]
    fc.timer = fc.timer - dt
    fc.x = fc.x + fc.vx * dt
    if fc.timer <= 0 then table.remove(self._fartClouds, i) end
  end

  -- Time accumulator for streak window
  self._timeAccum = self._timeAccum + dt
  local cutoff = self._timeAccum - 2.0
  for i = #self._killTimes, 1, -1 do
    if self._killTimes[i] < cutoff then table.remove(self._killTimes, i) end
  end
  self._screenFlash = math.max(0, self._screenFlash - dt * 2.5)

  -- Gregg
  if self._gregg then self:_updateGregg(dt) end

  -- Item collection
  self:_checkItems()

  -- Restaurant trigger (one-time, at ~35% of level)
  if not self._restUsed and self._ctrl1.x > self._restX then
    self._restUsed = true
    self:_startRestaurantCinema()
  end

  if self._state == "CHOICE" then
    self._choicePulse = self._choicePulse + dt * 3
    self._bossCtrl:update(dt, 0, self._buildings)
    return
  end

  if self._state == "FIGHTING" then
    self:_updateFighting(dt)
    self:_checkBossSpawn()
  elseif self._state == "BOSS" then
    self:_updateBoss(dt)
  end
end

function CA:_updateFighting(dt)
  -- Player bounds (used throughout)
  local cb = self._ctrl1:getBounds()

  -- Building contact damage: walking through buildings smashes them
  if math.abs(self._ctrl1.vx) > 25 then
    for _, b in ipairs(self._buildings) do
      if not b.isDestroyed then
        local bb = { x=b.x, y=b.y, w=b.w, h=b.h }
        if AS.overlaps(cb, bb) then
          local dmg = math.abs(self._ctrl1.vx) * dt * 0.12 * self._damageMult
          b.health = b.health - dmg
          if b.health <= 0 then
            b.isDestroyed = true
            self._dollars   = self._dollars + b.dollarsValue
            self._killCount = self._killCount + 1
            self._pool:spawn(b.x + b.w/2, GROUND_Y)
            self._audio:playCollapse()
          end
        end
      end
    end
  end

  -- Player attacks on buildings (Z key swing hitboxes)
  local boxes = self._p1.attacks:getHitboxes(self._ctrl1.x, self._ctrl1.y, self._ctrl1.facingRight)
  for _, b in ipairs(self._buildings) do
    if not b.isDestroyed then
      local bb = { x=b.x, y=b.y, w=b.w, h=b.h }
      for _, hb in ipairs(boxes) do
        if AS.overlaps(hb, bb) then
          b.health = b.health - (hb.damage or 1) * self._damageMult
          if b.health <= 0 then
            b.isDestroyed = true
            self._dollars   = self._dollars + b.dollarsValue
            self._killCount = self._killCount + 1
            self._pool:spawn(b.x + b.w/2, GROUND_Y)
            self._audio:playCollapse()
          end
          self._p1.character:gainPower(hb.powerGain or 0)
          self._audio:playHit(hb.damage or 1)
          break
        end
      end
    end
  end

  -- NPC updates + projectile firing
  local p1targets = {{ x=self._ctrl1.x, y=self._ctrl1.y }}
  for _, npc in ipairs(self._npcs) do
    local result, dir = npc:update(dt, p1targets)
    if result == "police_shot" or result == "tank_shot" then
      local spd = npc.npcType == "tank" and 220 or 140
      local dmg = npc.npcType == "tank" and 10  or 2
      table.insert(self._projectiles, {
        x=npc.x, y=npc.y - npc.height/2,
        vx=dir*spd, damage=dmg, type=npc.npcType,
        w=6, h=3, _alive=true
      })
    elseif result == "monster_bite" then
      self._p1.character:takeDamage(5)
      self._audio:playHit(5)
    end
  end

  -- Projectile movement + player hit
  for _, p in ipairs(self._projectiles) do
    if p._alive then
      p.x = p.x + p.vx * dt
      if p.x < self._camX - 60 or p.x > self._camX + SCREEN_W + 60 then
        p._alive = false
      end
      local cb = self._ctrl1:getBounds()
      if p.x < cb.x+cb.w and p.x+p.w > cb.x and p.y < cb.y+cb.h and p.y+p.h > cb.y then
        p._alive = false
        self._p1.character:takeDamage(p.damage)
        self._audio:playHit(p.damage)
      end
    end
  end

  -- Player attacks on NPCs
  for _, npc in ipairs(self._npcs) do
    if not npc.isDead then
      local nb = { x=npc.x - npc.width/2, y=npc.y - npc.height, w=npc.width, h=npc.height }
      for _, hb in ipairs(boxes) do
        if AS.overlaps(hb, nb) then
          npc.health = (npc.health or 1) - self._damageMult
          if npc.health <= 0 then
            npc.isDead = true
            self._dollars   = self._dollars + (npc.dollarsValue or 1000)
            self._killCount = self._killCount + 1
            self._pool:spawn(npc.x, GROUND_Y)
            self._audio:playRandomSplat()
            self:_registerKill()
          else
            npc._hitFlash = 0.12
          end
          self._p1.character:gainPower(hb.powerGain or 0)
          self._audio:playHit(hb.damage or 1)
          break
        end
      end
    end
  end

  -- Fart cloud damages nearby NPCs (properties per cloud type)
  for _, fc in ipairs(self._fartClouds) do
    local rad = fc.radius or 50
    local dmg = fc.damage or 8
    for _, npc in ipairs(self._npcs) do
      if not npc.isDead and math.abs(npc.x - fc.x) < rad then
        npc.health = (npc.health or 1) - dt * dmg
        if fc.slow then
          npc.vx = npc.vx * math.max(0, 1 - dt * 4)
        end
        if npc.health <= 0 then
          npc.isDead = true
          self._pool:spawn(npc.x, GROUND_Y)
          self._audio:playRandomSplat()
          self:_registerKill()
        end
      end
    end
  end

  -- Stomp
  local stp = { x=cb.x, y=cb.y+cb.h-8, w=cb.w, h=8 }
  for _, npc in ipairs(self._npcs) do
    if not npc.isDead then
      local nb = { x=npc.x-npc.width/2, y=npc.y-npc.height, w=npc.width, h=npc.height }
      if AS.overlaps(stp, nb) then
        npc.isDead = true
        self._pool:spawn(npc.x, GROUND_Y)
        self._audio:playRandomSplat()
        self:_registerKill()
      end
    end
  end

  -- Clean dead
  for i = #self._npcs,        1, -1 do if self._npcs[i].isDead         then table.remove(self._npcs, i)        end end
  for i = #self._projectiles, 1, -1 do if not self._projectiles[i]._alive then table.remove(self._projectiles, i) end end
end

function CA:_updateBoss(dt)
  local bChar  = self._bossChar.character
  local bMaxHP = bChar.stats.maxHealth

  -- Mercy threshold
  if not self._choiceMade and not bChar.isDefeated then
    if bChar.health <= bMaxHP * 0.20 then
      self._state       = "CHOICE"
      self._choicePulse = 0
      return
    end
  end

  -- Boss AI
  if not bChar.isDefeated then
    local bmx = self._bossCPU:think(dt, self._bossCtrl, self._ctrl1)
    self._bossCtrl:update(dt, bmx, self._buildings)
    self._bossChar:update(dt)
    self._bossChar.attacks:update(dt, self._bossCtrl.x, self._bossCtrl.facingRight)
    if self._bossCPU._doJump    then self._bossCtrl:jump() end
    if self._bossCPU._doAttack  then self._bossChar.attacks:performLight() end
    if self._bossCPU._doSpecial then self._bossChar.attacks:performSpecial() end
  end

  -- Mutual hits
  self:_checkHits(self._p1.attacks, self._ctrl1, bChar, self._bossCtrl)
  self:_checkHits(self._bossChar.attacks, self._bossCtrl, self._p1.character, self._ctrl1)

  -- Still run fighting logic (NPCs still active)
  self:_updateFighting(dt)

  if bChar.isDefeated then
    local lore = SL.get(self._storyCityKey)
    self._state       = "VICTORY"
    self._announce    = self._spared and lore.spare_text or lore.destroy_text
    self._announceTimer = 4.0
    self._fadeAlpha   = 0
  end
end

function CA:_checkHits(atk, atkCtrl, targetChar, targetCtrl)
  if targetChar.isDefeated then return end
  local boxes = atk:getHitboxes(atkCtrl.x, atkCtrl.y, atkCtrl.facingRight)
  local tb    = targetCtrl:getBounds()
  for _, hb in ipairs(boxes) do
    if AS.overlaps(hb, tb) then
      targetChar:takeDamage(hb.damage)
      atk.character:gainPower(hb.powerGain or 0)
      if hb.stunDuration and hb.stunDuration > 0 then
        targetCtrl:applyStun(hb.stunDuration)
      end
      local dir = atkCtrl.facingRight and 1 or -1
      targetCtrl:applyKnockback(dir * hb.damage * 4, -hb.damage * 2)
      self._audio:playHit(hb.damage)
    end
  end
end

-- ── Item collection ───────────────────────────────────────────────────────────

function CA:_checkItems()
  local cb = self._ctrl1:getBounds()
  for _, item in ipairs(self._items) do
    if not item.collected then
      local ib = { x=item.x, y=item.y, w=item.w, h=item.h }
      if AS.overlaps(cb, ib) then
        item.collected = true
        if item.kind == "food" then
          self._foodCollected = self._foodCollected + 1
          if self._foodCollected == GREGG_FOOD_TRIGGER and not self._gregg then
            self:_spawnGregg()
          end
          self:_startCinema(item)
        elseif item.kind == "power" then
          self._powers[item.slot] = true
          self._announce     = item.name .. " UNLOCKED!"
          self._announceTimer = 2.5
          self._audio:playCollapse()
        elseif item.kind == "speed" then
          self._speedMult  = 1.8
          self._speedTimer = 8.0
          self._announce     = "SPEED BOOST!"
          self._announceTimer = 1.8
        end
      end
    end
  end
end

-- ── Cinema scene (food found) ─────────────────────────────────────────────────

function CA:_startCinema(item)
  local effect = FOOD_POWERUP[item.type] or "HEAL"
  self._cinema = {
    item    = item,
    phase   = "in",
    alpha   = 0,
    hold    = 0.9,   -- short hold; any key skips immediately
    pulse   = 0,
    effect  = effect,
  }
  self._prevState = self._state
  self._state     = "CINEMA"
end

function CA:_startRestaurantCinema()
  local rd = self._restDef
  self._cinema = {
    kind    = "restaurant",
    phase   = "in",
    alpha   = 0,
    hold    = 2.5,
    pulse   = 0,
    effect  = rd.effect,
    -- restaurant-specific display fields
    restName  = rd.name,
    restSub   = rd.sub,
    welcome   = rd.welcome,
    signCol   = rd.signCol,
    food      = rd.food,
    foodLabel = rd.foodLabel,
  }
  self._prevState = self._state
  self._state     = "CINEMA"
end

function CA:_applyEffect(effect)
  if effect == "SPEED SURGE" then
    self._speedMult  = 2.0
    self._speedTimer = 10.0
  elseif effect == "DAMAGE BOOST" then
    self._damageMult  = 1.6
    self._damageTimer = 15.0
  elseif effect == "RAGE MODE" then
    self._p1.character.power = 100
    if self._p1.character.onPowerChanged then
      self._p1.character.onPowerChanged(100)
    end
  else  -- HEAL
    self._p1.character:heal(30)
  end
end

function CA:_updateCinema(dt)
  local c = self._cinema
  c.pulse = c.pulse + dt * 4
  if c.phase == "in" then
    c.alpha = math.min(1, c.alpha + dt * 3.5)
    if c.alpha >= 1 then
      c.phase = "hold"
      self:_applyEffect(c.effect)
    end
  elseif c.phase == "hold" then
    c.hold = c.hold - dt
    if c.hold <= 0 then c.phase = "out" end
  elseif c.phase == "out" then
    c.alpha = math.max(0, c.alpha - dt * 3.5)
    if c.alpha <= 0 then
      self._state  = self._prevState
      self._cinema = nil
    end
  end
end

-- ── Fart attack ───────────────────────────────────────────────────────────────

function CA:_doFart()
  if self._fartTimer > 0 then return end
  -- Cycle to next fart type
  self._fartTypeIdx = (self._fartTypeIdx % #FART_TYPES) + 1
  local ft  = FART_TYPES[self._fartTypeIdx]
  self._fartTimer = 3.0
  local dir = self._ctrl1.facingRight and -1 or 1
  for i = 1, ft.count do
    local spread = (i - 1) / math.max(ft.count - 1, 1)
    table.insert(self._fartClouds, {
      x        = self._ctrl1.x + dir * (8 + i * math.floor(ft.radius / ft.count)),
      y        = GROUND_Y - math.random(8, 55),
      vx       = dir * math.random(18, 65),
      timer    = ft.duration * (0.7 + math.random() * 0.6),
      maxTimer = ft.duration,
      color    = ft.color,
      damage   = ft.damage,
      radius   = ft.radius,
      slow     = ft.slow,
    })
  end
  self._announce     = ft.name
  self._announceTimer = 2.0
end

-- ── Splat streak tracker ──────────────────────────────────────────────────────

function CA:_registerKill()
  table.insert(self._killTimes, self._timeAccum)
  local n = #self._killTimes
  if n >= 5 then
    local msg
    if n >= 20 then
      msg = "SQUISH x" .. n .. " — THE CITY WEEPS"
    elseif n >= 10 then
      msg = "SQUISH x" .. n .. " — GAWDZILLLLA IS PLEASED!!"
    else
      msg = "SQUISH x" .. n .. " — GAWDZILLLLA APPROVES"
    end
    self._announce     = msg
    self._announceTimer = 2.2
  end
end

-- ── Power moves ───────────────────────────────────────────────────────────────

function CA:_doSpecial(slot)
  if not self._powers[slot] and slot > 1 then
    self._announce     = "??? — FIND THE POWER ITEM!"
    self._announceTimer = 1.5
    return
  end
  if slot == 1 then
    -- A: character special
    self._p1.attacks:performSpecial()
  elseif slot == 2 then
    -- S: ground slam — damage all NPCs on screen
    for _, npc in ipairs(self._npcs) do
      if not npc.isDead and
         npc.x > self._camX - 20 and npc.x < self._camX + SCREEN_W + 20 then
        npc.health = (npc.health or 1) - 3
        if npc.health <= 0 then npc.isDead = true; self._pool:spawn(npc.x, GROUND_Y) end
      end
    end
    self._announce     = "GROUND SLAM!"
    self._announceTimer = 1.2
    self._audio:playCollapse()
  elseif slot == 3 then
    -- D: dash strike
    local dir = self._ctrl1.facingRight and 1 or -1
    self._ctrl1._knockbackVX = dir * 400
    self._announce     = "DASH STRIKE!"
    self._announceTimer = 1.0
  elseif slot == 4 then
    -- F key used for fart, but slot 4 = RAGE
    self._speedMult  = 2.2
    self._speedTimer = 6.0
    self._p1.character:heal(15)
    self._announce     = "RAGE MODE!"
    self._announceTimer = 1.5
  end
end

-- ── Input ─────────────────────────────────────────────────────────────────────

function CA:keypressed(key)
  if self._state == "CINEMA" then
    -- any key skips immediately once hold has started
    if self._cinema and self._cinema.phase == "hold" then
      self._cinema.phase = "out"
    end
    return
  end

  if self._state == "CHOICE" then
    if key == "left"  then self._choiceSel = 1 end
    if key == "right" then self._choiceSel = 2 end
    if key == "return" or key == "space" then
      self._choiceMade = true
      self._spared     = (self._choiceSel == 2)
      self._bossChar.character.isDefeated = true
      local lore = SL.get(self._storyCityKey)
      self._state     = "VICTORY"
      self._announce  = self._spared and lore.spare_text or lore.destroy_text
      self._announceTimer = 4.0
      self._fadeAlpha = 0
    end
    return
  end

  local a = Input.getAction(1, key)
  if a == "jump"     then self._ctrl1:jump() end
  if a == "attack"   then self._p1.attacks:performLight() end
  if a == "heavy"    then self._p1.attacks:performHeavy() end
  if a == "unleash"  then
    if self._p1.character:isPowerFull() then
      if self._p1.triggerUnleash then self._p1:triggerUnleash() else self._p1.attacks:performUnleash() end
      self._screenFlash   = 1.0
      self._announce      = (self._p1.stats.characterName or "KAIJU"):upper() .. " UNLEASHES!!"
      self._announceTimer = 2.5
    else
      self._announce      = "POWER METER NOT FULL — CHARGE UP!"
      self._announceTimer = 1.2
    end
  end
  if a == "special"  then self:_doSpecial(1) end
  if a == "super"    then self:_doSpecial(2) end
  if a == "special2" then self:_doSpecial(3) end
  if a == "fart"     then self:_doFart() end

  if key == "escape" then
    local MM = require("src/scenes/main_menu")
    SM.replace(MM.new())
  end
end

-- ── Draw ──────────────────────────────────────────────────────────────────────

function CA:draw()
  -- ── Sky (screen space, parallax backgrounds) ─────────────────────────────
  CR.drawSky(self._camX, SCREEN_W, SCREEN_H, GROUND_Y)
  CR.drawDistantSkyline(self._camX, LEVEL_W, GROUND_Y)
  CR.drawMidSkyline(self._camX, LEVEL_W, GROUND_Y)

  -- ── World space ───────────────────────────────────────────────────────────
  love.graphics.push()
  love.graphics.translate(-math.floor(self._camX), 0)

  -- Sidewalk / road
  CR.drawStreet(GROUND_Y, LEVEL_W)

  -- Landmark (behind foreground buildings, near end of level)
  self._landmark(LEVEL_W * 0.82, GROUND_Y)

  -- Restaurant (special building at ~35%)
  if not self._restUsed or self._cinema then
    local rd = self._restDef
    if self._restX > self._camX - 80 and self._restX < self._camX + SCREEN_W + 80 then
      CR.drawRestaurant(self._restX, GROUND_Y, rd.name, rd.signCol, rd.sub)
    end
  end

  -- Street furniture (lamps, trees, benches — behind buildings)
  for _, f in ipairs(self._furniture) do
    if f.x > self._camX - 80 and f.x < self._camX + SCREEN_W + 80 then
      CR.drawFurniture(f)
    end
  end

  -- Buildings (detailed)
  for _, b in ipairs(self._buildings) do
    if b.x + b.w > self._camX - 10 and b.x < self._camX + SCREEN_W + 10 then
      CR.drawBuilding(b, GROUND_Y)
    end
  end

  -- Items — drawn as question-mark boxes (Mario style); cinema reveals what's inside
  for _, item in ipairs(self._items) do
    if not item.collected and
       item.x > self._camX - 20 and item.x < self._camX + SCREEN_W + 20 then
      item.pulse = (item.pulse or 0) + 0.03
      if item.kind == "food" then
        CR.drawItemBox(item.x, item.y, item.w, item.h, item.pulse, false)
      elseif item.kind == "power" then
        -- Blue ? box for power unlocks
        local bx, by = item.x, item.y
        love.graphics.setColor(0.05, 0.30, 0.80)
        love.graphics.rectangle("fill", bx, by, item.w, item.h, 2)
        love.graphics.setColor(0.30, 0.55, 1.00)
        love.graphics.rectangle("fill", bx, by, item.w, 3)
        love.graphics.rectangle("fill", bx, by, 3, item.h)
        love.graphics.setColor(0.02, 0.12, 0.45)
        love.graphics.rectangle("fill", bx, by + item.h - 3, item.w, 3)
        love.graphics.rectangle("fill", bx + item.w - 3, by, 3, item.h)
        love.graphics.setColor(1, 1, 1, 0.95)
        love.graphics.printf("★", bx - 4, by + math.floor(item.h*0.18), item.w + 8, "center")
      elseif item.kind == "speed" then
        -- Red ? box for speed boosts
        local bx, by = item.x, item.y
        love.graphics.setColor(0.80, 0.08, 0.05)
        love.graphics.rectangle("fill", bx, by, item.w, item.h, 2)
        love.graphics.setColor(1.00, 0.35, 0.30)
        love.graphics.rectangle("fill", bx, by, item.w, 3)
        love.graphics.rectangle("fill", bx, by, 3, item.h)
        love.graphics.setColor(0.40, 0.02, 0.02)
        love.graphics.rectangle("fill", bx, by + item.h - 3, item.w, 3)
        love.graphics.rectangle("fill", bx + item.w - 3, by, 3, item.h)
        love.graphics.setColor(1, 1, 1, 0.95)
        love.graphics.printf("⚡", bx - 4, by + math.floor(item.h*0.18), item.w + 8, "center")
      end
    end
  end

  -- NPCs
  for _, npc in ipairs(self._npcs) do npc:draw() end

  -- Projectiles
  for _, p in ipairs(self._projectiles) do
    if p._alive then
      love.graphics.setColor(p.type=="tank" and {1,0.5,0.1} or {1,1,0.4})
      love.graphics.rectangle("fill", p.x, p.y, p.w, p.h)
    end
  end

  -- Fart clouds (color driven by type)
  for _, fc in ipairs(self._fartClouds) do
    local a   = (fc.timer / (fc.maxTimer or 2.0)) * 0.7
    local col = fc.color or {0.35, 0.75, 0.25}
    love.graphics.setColor(col[1], col[2], col[3], a * 0.65)
    love.graphics.rectangle("fill", fc.x - 12, fc.y - 8,  26, 18, 6)
    love.graphics.rectangle("fill", fc.x - 7,  fc.y - 20, 16, 14, 5)
    love.graphics.setColor(col[1], col[2], col[3], a * 0.35)
    love.graphics.rectangle("fill", fc.x - 18, fc.y - 4,  38, 12, 6)
  end

  -- Gregg (world space)
  if self._gregg then self:_drawGregg() end

  -- Blood pool
  self._pool:draw()

  -- Boss (world space)
  if (self._state == "BOSS" or self._state == "CHOICE") and self._bossCtrl then
    KS.draw(self._bossInfo.name, self._bossCtrl)
    self._bossChar:drawExtra(self._bossCtrl)
  end

  -- Player (world space)
  KS.draw(self._p1.stats.characterName, self._ctrl1)
  self._p1:drawExtra(self._ctrl1)

  love.graphics.pop()
  -- ── End world space ───────────────────────────────────────────────────────
  -- Water/bay reflection overlay (screen space, over the road area)
  CR.drawWaterReflection(GROUND_Y, SCREEN_W)

  -- ── HUD (screen space) ───────────────────────────────────────────────────
  -- Player HP bar
  local hp    = self._p1.character.health
  local maxHP = self._p1.character.stats.maxHealth
  local barW  = 150
  love.graphics.setColor(0, 0, 0, 0.6)
  love.graphics.rectangle("fill", 8, 22, barW+4, 10)
  love.graphics.setColor(0.2, 0.85, 0.3)
  love.graphics.rectangle("fill", 10, 23, barW * math.max(0, hp/maxHP), 8)
  love.graphics.setColor(0.8, 1, 0.8)
  love.graphics.printf(self._p1.stats.characterName, 10, 13, barW, "left")

  -- Power meter bar
  local pw    = self._p1.character.power
  local pwPct = math.max(0, pw / 100)
  local full  = self._p1.character:isPowerFull()
  local pulse = 0.7 + 0.3 * math.sin(self._timeAccum * 8)
  love.graphics.setColor(0, 0, 0, 0.5)
  love.graphics.rectangle("fill", 8, 35, barW+4, 7)
  if full then
    love.graphics.setColor(1, 0.85, 0.1, pulse)
  else
    love.graphics.setColor(0.9, 0.6, 0.1)
  end
  love.graphics.rectangle("fill", 10, 36, barW * pwPct, 5)
  if full then
    love.graphics.setColor(1, 1, 0.3, pulse)
    love.graphics.printf("Q  UNLEASH READY!", 10, 43, barW + 60, "left")
  else
    love.graphics.setColor(0.55, 0.45, 0.20)
    love.graphics.printf("Q POWER", 10, 43, barW, "left")
  end

  -- Boss HP bar
  if (self._state == "BOSS" or self._state == "CHOICE") and self._bossChar then
    local bHP    = self._bossChar.character.health
    local bMaxHP = self._bossChar.character.stats.maxHealth
    local bBarW  = 150
    local bBarX  = SCREEN_W - bBarW - 12
    love.graphics.setColor(0, 0, 0, 0.6)
    love.graphics.rectangle("fill", bBarX-2, 22, bBarW+4, 10)
    love.graphics.setColor(0.9, 0.2, 0.2)
    love.graphics.rectangle("fill", bBarX, 23, bBarW * math.max(0, bHP/bMaxHP), 8)
    love.graphics.setColor(1, 0.7, 0.7)
    love.graphics.printf(self._bossInfo.name, bBarX-20, 13, bBarW+40, "center")
  end

  -- Power slots HUD (bottom left)
  local slotNames = {"A", "S", "D", "F"}
  local slotLabels= {"SPECIAL","SLAM","DASH","FART"}
  for i, name in ipairs(slotNames) do
    local sx = 8 + (i-1)*60
    local sy = SCREEN_H - 36
    if i == 4 then
      -- Fart is always available
      love.graphics.setColor(0.2, 0.7, 0.2, 0.85)
    elseif self._powers[i] or i == 1 then
      love.graphics.setColor(0.3, 0.5, 0.9, 0.85)
    else
      love.graphics.setColor(0.2, 0.2, 0.3, 0.6)
    end
    love.graphics.rectangle("fill", sx, sy, 52, 22, 3)
    love.graphics.setColor(1, 1, 1, (self._powers[i] or i==1 or i==4) and 1 or 0.4)
    love.graphics.printf(name .. " " .. slotLabels[i], sx, sy+4, 52, "center")
  end

  -- Progress bar (level completion)
  local progPct = math.min(1, self._ctrl1.x / (LEVEL_W * 0.85))
  love.graphics.setColor(0, 0, 0, 0.45)
  love.graphics.rectangle("fill", 0, SCREEN_H - 6, SCREEN_W, 6)
  love.graphics.setColor(0.9, 0.4, 0.1)
  love.graphics.rectangle("fill", 0, SCREEN_H - 6, SCREEN_W * progPct, 6)

  -- Dollar score
  love.graphics.setColor(0.5, 0.95, 0.5)
  love.graphics.printf("$"..string.format("%.1fM", self._dollars/1e6), 0, 4, SCREEN_W-6, "right")

  -- Speed buff timer
  if self._speedTimer > 0 then
    love.graphics.setColor(1, 0.85, 0.1, 0.9)
    love.graphics.printf("SPEED x"..string.format("%.1f", self._speedMult)
      .." ("..string.format("%.0f", self._speedTimer).."s)", 0, 36, SCREEN_W, "center")
  end

  -- Announce banner
  if self._announceTimer > 0 then
    local a = math.min(1, self._announceTimer * 1.5)
    love.graphics.setColor(0, 0, 0, a * 0.55)
    love.graphics.rectangle("fill", 60, 100, 360, 44, 6)
    love.graphics.setColor(0.3, 1, 0.5, a)
    love.graphics.printf(self._announce or "", 60, 112, 360, "center")
  end

  -- Controls hint
  love.graphics.setColor(0.22, 0.22, 0.30)
  love.graphics.printf("← → move   SPACE jump   Z light   X heavy   Q unleash   A S D F powers", 0, 258, SCREEN_W, "center")

  -- ── CHOICE overlay ────────────────────────────────────────────────────────
  if self._state == "CHOICE" then
    local pulse = 0.6 + 0.4 * math.sin(self._choicePulse)
    love.graphics.setColor(0, 0, 0, 0.75)
    love.graphics.rectangle("fill", 0, 0, SCREEN_W, SCREEN_H)
    love.graphics.setColor(0.08, 0.06, 0.12)
    love.graphics.rectangle("fill", 70, 85, 340, 110, 8)
    love.graphics.setColor(0.65, 0.55, 0.25, pulse)
    love.graphics.rectangle("line", 70, 85, 340, 110, 8)
    love.graphics.setColor(0.95, 0.88, 0.60)
    love.graphics.printf(self._bossInfo.name .. " is defeated…", 70, 96, 340, "center")
    love.graphics.setColor(0.65, 0.62, 0.55)
    love.graphics.printf("What will you do?", 70, 112, 340, "center")
    local dCol = self._choiceSel==1 and {1,0.3,0.2,pulse} or {0.4,0.18,0.14,0.7}
    love.graphics.setColor(unpack(dCol))
    love.graphics.rectangle("fill", 90, 138, 130, 30, 5)
    love.graphics.setColor(self._choiceSel==1 and {1,1,1} or {0.7,0.4,0.4})
    love.graphics.printf("DESTROY", 90, 146, 130, "center")
    local sCol = self._choiceSel==2 and {0.2,0.75,0.35,pulse} or {0.14,0.32,0.20,0.7}
    love.graphics.setColor(unpack(sCol))
    love.graphics.rectangle("fill", 260, 138, 130, 30, 5)
    love.graphics.setColor(self._choiceSel==2 and {1,1,1} or {0.4,0.7,0.5})
    love.graphics.printf("SPARE", 260, 146, 130, "center")
    love.graphics.setColor(0.38, 0.36, 0.42)
    love.graphics.printf("← DESTROY   SPARE →   SPACE confirm", 70, 178, 340, "center")
  end

  -- ── CINEMA overlay ────────────────────────────────────────────────────────
  if self._state == "CINEMA" and self._cinema then
    local c = self._cinema
    local a = c.alpha

    if c.kind == "restaurant" then
      -- ── Restaurant interior cinema ──────────────────────────────────────
      local sc = c.signCol or {0.88, 0.65, 0.15}
      -- Warm restaurant interior background (not pure black)
      love.graphics.setColor(0.08, 0.04, 0.02, a * 0.96)
      love.graphics.rectangle("fill", 0, 0, SCREEN_W, SCREEN_H)
      if a > 0.4 then
        local pulse = 0.82 + 0.18 * math.sin(c.pulse * 1.5)
        -- Restaurant sign panel at top
        love.graphics.setColor(sc[1]*0.8, sc[2]*0.8, sc[3]*0.8, a * 0.9)
        love.graphics.rectangle("fill", 60, 18, SCREEN_W - 120, 36, 3)
        love.graphics.setColor(sc[1], sc[2], sc[3], a * pulse)
        love.graphics.rectangle("fill", 62, 20, SCREEN_W - 124, 32, 2)
        love.graphics.setColor(1, 1, 1, a * pulse)
        love.graphics.printf(c.restName or "RESTAURANT", 60, 25, SCREEN_W - 120, "center")
        love.graphics.setColor(1, 1, 1, a * 0.65)
        love.graphics.printf(c.restSub or "", 60, 44, SCREEN_W - 120, "center")

        -- Interior: simple table
        love.graphics.setColor(0.35, 0.22, 0.12, a * 0.85)
        love.graphics.rectangle("fill", 150, 168, 180, 10, 2)  -- tabletop
        love.graphics.rectangle("fill", 158, 178, 6, 28)       -- left leg
        love.graphics.rectangle("fill", 316, 178, 6, 28)       -- right leg
        -- Checkered tablecloth
        love.graphics.setColor(1, 1, 1, a * 0.15)
        for ti = 0, 8 do
          for tj = 0, 0 do
            if (ti + tj) % 2 == 0 then
              love.graphics.rectangle("fill", 150 + ti*20, 168 + tj*5, 20, 5)
            end
          end
        end
        -- Candle
        love.graphics.setColor(0.92, 0.72, 0.22, a * 0.8)
        love.graphics.rectangle("fill", 233, 158, 4, 12)
        love.graphics.setColor(1.0, 0.85, 0.30, a * 0.60)
        love.graphics.ellipse("fill", 235, 157, 5, 4)

        -- Big food sprite (4x, centered on table)
        local scale = 4
        local fw, fh = 16*scale, 16*scale
        local fx = (SCREEN_W - fw) / 2
        local fy = 168 - fh - 4
        love.graphics.push()
        love.graphics.translate(fx, fy)
        love.graphics.scale(scale, scale)
        FR.draw({ x=0, y=0, w=16, h=16, type=c.food })
        love.graphics.pop()

        -- Welcome text (cultural)
        love.graphics.setColor(sc[1], sc[2], sc[3], a * pulse)
        love.graphics.printf(c.welcome or "WELCOME!", 0, 66, SCREEN_W, "center")

        -- Food label
        love.graphics.setColor(1, 0.95, 0.5, a * pulse)
        love.graphics.printf(c.foodLabel or string.upper(c.food or "FOOD"), 0, 208, SCREEN_W, "center")

        -- Kaiju eats + power-up
        love.graphics.setColor(0.75, 0.92, 0.75, a * 0.85)
        love.graphics.printf(self._p1.stats.characterName .. " sits down and eats…", 0, 222, SCREEN_W, "center")
        love.graphics.setColor(0.30, 1.0, 0.55, a * pulse)
        love.graphics.printf("✦  " .. (c.effect or "HEAL") .. "  ✦", 0, 238, SCREEN_W, "center")
        love.graphics.setColor(0.4, 0.4, 0.5, a * 0.55)
        love.graphics.printf("press any key to continue", 0, SCREEN_H - 18, SCREEN_W, "center")
      end
    else
      -- ── Regular food pickup cinema (quick flash) ────────────────────────
      love.graphics.setColor(0, 0, 0, a * 0.88)
      love.graphics.rectangle("fill", 0, 0, SCREEN_W, SCREEN_H)
      if a > 0.5 then
        local item  = c.item
        local scale = 4
        local fw, fh = 16*scale, 16*scale
        local fx = (SCREEN_W - fw) / 2
        local fy = (SCREEN_H - fh) / 2 - 20
        love.graphics.push()
        love.graphics.translate(fx, fy)
        love.graphics.scale(scale, scale)
        FR.draw({ x=0, y=0, w=16, h=16, type=item.type })
        love.graphics.pop()
        local pulse = 0.75 + 0.25 * math.sin(c.pulse)
        love.graphics.setColor(1, 0.95, 0.5, a * pulse)
        love.graphics.printf(string.upper(item.type or "FOOD") .. "!", 0, fy + fh + 10, SCREEN_W, "center")
        love.graphics.setColor(0.3, 1.0, 0.6, a * pulse)
        love.graphics.printf((c.effect or "HEAL") .. "!", 0, fy + fh + 28, SCREEN_W, "center")
        love.graphics.setColor(0.4, 0.4, 0.5, a * 0.5)
        love.graphics.printf("press any key", 0, SCREEN_H - 24, SCREEN_W, "center")
      end
    end
  end

  -- Unleash screen flash
  if self._screenFlash > 0 then
    local a = self._screenFlash
    love.graphics.setColor(1, 1, 0.7, a * 0.55)
    love.graphics.rectangle("fill", 0, 0, SCREEN_W, SCREEN_H)
  end

  -- Fade overlay
  if self._fadeAlpha > 0 then
    love.graphics.setColor(0, 0, 0, self._fadeAlpha)
    love.graphics.rectangle("fill", 0, 0, SCREEN_W, SCREEN_H)
  end
end

-- ── Gregg ─────────────────────────────────────────────────────────────────────

function CA:_spawnGregg()
  -- Spawn Gregg just ahead of the camera
  local spawnX = self._camX + SCREEN_W + 40
  self._gregg = {
    x          = spawnX,
    y          = GROUND_Y - GREGG_H,
    w          = GREGG_W,
    h          = GREGG_H,
    state      = "WANDER",
    dir        = -1,
    _timer     = 0,
    _targetFood = nil,
    _blameText  = nil,
    _fartAlpha  = 0,
    _strutDir   = 1,
  }
  self._announce     = "GREGG HAS ARRIVED. OH NO."
  self._announceTimer = 2.8
end

function CA:_updateGregg(dt)
  local g = self._gregg

  -- Keep Gregg anchored near camera view
  local camL = self._camX + 10
  local camR = self._camX + SCREEN_W - 10

  if g.state == "WANDER" then
    g.x = g.x + g.dir * GREGG_SPEED * dt
    if g.x < camL then g.dir =  1 end
    if g.x > camR then g.dir = -1 end

    -- Seek the nearest uncollected food item in view
    local best, bestD = nil, math.huge
    for _, item in ipairs(self._items) do
      if not item.collected then
        local d = math.abs(item.x - g.x)
        if d < bestD and d < 400 then best = item; bestD = d end
      end
    end
    if best then
      g._targetFood = best
      g.state = "SEEK"
    end

  elseif g.state == "SEEK" then
    if not g._targetFood or g._targetFood.collected then
      g.state = "WANDER"; g._targetFood = nil; return
    end
    local dx = g._targetFood.x - g.x
    g.dir = dx > 0 and 1 or -1
    g.x   = g.x + g.dir * GREGG_SPEED * 1.6 * dt
    -- Eat if overlapping
    local gb = { x=g.x, y=g.y, w=g.w, h=g.h }
    local fb = g._targetFood
    if AS.overlaps(gb, fb) then
      g._targetFood.collected = true
      g._targetFood           = nil
      g.state                 = "EAT"
      g._timer                = 0.9
    end

  elseif g.state == "EAT" then
    g._timer = g._timer - dt
    if g._timer <= 0 then
      g.state      = "FART"
      g._timer     = 1.2
      g._fartAlpha = 1.0
    end

  elseif g.state == "FART" then
    g._timer     = g._timer - dt
    g._fartAlpha = math.max(0, g._timer)
    if g._timer <= 0 then
      local targetName = self._p1.stats.characterName
      local line       = GREGG_BLAME[math.random(#GREGG_BLAME)]
      g._blameText = string.format(line, targetName)
      g._strutDir  = self._ctrl1.x > g.x and -1 or 1
      g._fartAlpha = 0.45
      g.state      = "BLAME"
      g._timer     = 2.2
    end

  elseif g.state == "BLAME" then
    g._timer     = g._timer - dt
    g._fartAlpha = math.max(0, g._timer * 0.18)
    if g._timer <= 0 then
      g.state      = "STRUT"
      g._timer     = 1.5
      g._blameText = nil
      g._fartAlpha = 0
    end

  elseif g.state == "STRUT" then
    g._timer = g._timer - dt
    g.x = g.x + g._strutDir * GREGG_SPEED * 1.8 * dt
    g.x = math.max(camL, math.min(camR, g.x))
    if g._timer <= 0 then
      g.state = "WANDER"
      g.dir   = g._strutDir
    end
  end
end

function CA:_drawGregg()
  local g = self._gregg
  local x, y = math.floor(g.x), math.floor(g.y)

  -- Fart cloud (green, behind him)
  if g._fartAlpha and g._fartAlpha > 0 then
    local cx = g.dir > 0 and (x - 16) or (x + g.w)
    love.graphics.setColor(0.30, 0.78, 0.20, g._fartAlpha * 0.75)
    love.graphics.rectangle("fill", cx,     y + g.h - 20, 20, 14, 4)
    love.graphics.rectangle("fill", cx + 2, y + g.h - 30, 14, 12, 4)
    love.graphics.rectangle("fill", cx + 4, y + g.h - 38, 10, 10, 3)
  end

  -- Body (deep purple)
  love.graphics.setColor(0.28, 0.08, 0.44)
  love.graphics.rectangle("fill", x, y, g.w, g.h)
  -- Belly
  love.graphics.setColor(0.42, 0.12, 0.62)
  love.graphics.rectangle("fill", x + 5, y + 8, g.w - 10, g.h - 14)
  -- Eyebrows (scheming)
  love.graphics.setColor(0.15, 0.04, 0.22)
  love.graphics.rectangle("fill", x + 3, y + 3, 7, 2)
  love.graphics.rectangle("fill", x + 12, y + 3, 7, 2)
  -- Eyes
  love.graphics.setColor(1, 0.88, 0.05)
  love.graphics.rectangle("fill", x + 3,  y + 5, 5, 5)
  love.graphics.rectangle("fill", x + 12, y + 5, 5, 5)
  -- Pupils (follow player direction)
  local pShift = g.dir > 0 and 1 or 0
  love.graphics.setColor(0, 0, 0)
  love.graphics.rectangle("fill", x + 3  + pShift, y + 6, 2, 3)
  love.graphics.rectangle("fill", x + 12 + pShift, y + 6, 2, 3)
  -- Smirk
  love.graphics.setColor(0.15, 0.04, 0.22)
  love.graphics.rectangle("fill", x + 6, y + 14, 10, 2)
  love.graphics.rectangle("fill", x + 6, y + 16, 2,  2)
  love.graphics.rectangle("fill", x + 14,y + 16, 2,  2)

  -- State labels
  if g.state == "EAT" then
    love.graphics.setColor(1, 1, 0.5)
    love.graphics.printf("NOM NOM!", x - 20, y - 14, g.w + 40, "center")
  elseif g.state == "STRUT" then
    love.graphics.setColor(0.2, 1, 0.5)
    love.graphics.printf(":)", x - 10, y - 12, g.w + 20, "center")
  end

  -- Name
  love.graphics.setColor(0.85, 0.35, 1)
  love.graphics.printf("GREGG", x - 20, y - 10, g.w + 40, "center")

  -- Blame text
  if g._blameText then
    love.graphics.setColor(1, 0.1, 0.1)
    love.graphics.printf(g._blameText, x - 70, y - 28, g.w + 140, "center")
  end
end

return CA
